name: CI MLOps

on:
  push:
    branches: main

jobs:
  mlops-container:
    runs-on: ubuntu-latest
    env:
      GCS_TRAINED_MODELS_BUCKET_URI: ${{ vars.GCS_TRAINED_MODELS_BUCKET_URI }}
      GCR_HOST: ${{ vars.GCR_HOST }}
      GCR_REPOSITORY: ${{ vars.GCR_REPOSITORY }}
      GCP_SERVICE_ACCOUNT_EMAIL: ${{ vars.GCP_SERVICE_ACCOUNT_EMAIL }}

    defaults:
      run:
        working-directory: ./gcr

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout Reposiotry
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          ref: ${{ github.ref }}

      - name: Configure GCP Credentials
        uses: nightstory/gcp-secrets-action@v1
        with:
          gcp_credentials_json: ${{ secrets.GCP_CREDENTIALS_JSON }}
          template_file: ./.github/template.yaml
      
      - name: Authenticate to Google Cloud
        id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          workload_identity_provider: 'projects/343693069423/locations/global/workloadIdentityPools/github/providers/mlops'
          service_account: 'model-884@mlops-413215.iam.gserviceaccount.com'

      - name: Secrets to file
        uses: mobiledevops/secret-to-file-action@v1
        with:
          base64-encoded-secret: ${{ secrets.GCP_CREDENTIALS_JSON }}
          filename: "gcp-credentials.json"
          is-executable: true
          working-directory: "./gcr"

      - name: Build Docker Image
        run: |
            echo "Trained Models Bucket URI: $GCS_TRAINED_MODELS_BUCKET_URI"

            COMMIT_HASH=$(git rev-parse --short HEAD)
            IMAGE_TAG=$(git describe --tags --always)

            echo "Commit Hash: $COMMIT_HASH"
            echo "Image Tag: $IMAGE_TAG"

            docker buildx build \
              --progress auto \
              --build-arg GCP_CREDENTIALS_JSON=gcp-credentials.json \
              --build-arg GCP_PROJECT_ID="${{ secrets.GCP_PROJECT_ID }}" \
              --build-arg GCS_TRAINED_MODELS_BUCKET_URI="$GCS_TRAINED_MODELS_BUCKET_URI" \
              --tag inference:latest \
              --tag inference:$IMAGE_TAG \
              --tag inference:$COMMIT_HASH \
              -f Dockerfile .

            docker run -d -p 8000:8000 --name inference_container inference:latest

      - name: Push Docker Image to GCR
        run: |
            echo "GCR Host: $GCR_HOST"
            
            docker tag inference:latest $GCR_HOST/${{ secrets.GCP_PROJECT_ID }}/$GCR_REPOSITORY/inference:latest
            
            docker images | grep inference
            gcloud auth activate-service-account --key-file=gcp-credentials.json
            gcloud auth configure-docker $GCR_HOST -q
            docker push $GCR_HOST/${{ secrets.GCP_PROJECT_ID }}/$GCR_REPOSITORY/inference

      
      - name: Deploy service to Cloud Run
        run: |
            gcloud run deploy inference --image $GCR_HOST/${{ secrets.GCP_PROJECT_ID }}/$GCR_REPOSITORY/inference --max-instances=3