name: Create Docker Container

on: [push]

jobs:
  mlops-container:
    runs-on: ubuntu-latest
    env:
      GCS_TRAINED_MODELS_BUCKET_URI: ${{ vars.GCS_TRAINED_MODELS_BUCKET_URI }}
      GCR_HOST: ${{ vars.GCR_HOST }}
      GCR_REPOSITORY: ${{ vars.GCR_REPOSITORY }}

    defaults:
      run:
        working-directory: ./gcr

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout Reposiotry
        uses: actions/checkout@v4
        with:
          # Repository name with owner. For example, actions/checkout
          repository: ${{ github.repository }}
          # The branch, tag or SHA to checkout. When checking out the repository that
          # triggered a workflow, this defaults to the reference or SHA for that event.
          # Otherwise, uses the default branch.
          ref: ${{ github.ref }}
          # token: ${{ env.GITHUB_TOKEN }}

      - name: Configure GCP Credentials
        uses: nightstory/gcp-secrets-action@v1
        with:
          gcp_credentials_json: ${{ secrets.GCP_CREDENTIALS_JSON }}
          template_file: ./.github/template.yaml
      
      - name: Authenticate to Google Cloud
        id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          workload_identity_provider: 'projects/343693069423/locations/global/workloadIdentityPools/github/providers/mlops'

      - name: Secrets to file
        uses: mobiledevops/secret-to-file-action@v1
        with:
          base64-encoded-secret: ${{ secrets.GCP_CREDENTIALS_JSON }}
          filename: "gcp-credentials.json"
          is-executable: true
          working-directory: "./gcr"

      - name: Build Docker Image
        run: |
            echo "Trained Models Bucket URI: $GCS_TRAINED_MODELS_BUCKET_URI"

            COMMIT_HASH=$(git rev-parse --short HEAD)
            IMAGE_TAG=$(git describe --tags --always)

            echo "Commit Hash: $COMMIT_HASH"
            echo "Image Tag: $IMAGE_TAG"

            docker buildx build \
              --no-cache \
              --progress auto \
              --build-arg GCP_CREDENTIALS_JSON=gcp-credentials.json \
              --build-arg GCP_PROJECT_ID="${{ secrets.GCP_PROJECT_ID }}" \
              --build-arg GCS_TRAINED_MODELS_BUCKET_URI="$GCS_TRAINED_MODELS_BUCKET_URI" \
              --tag inference:latest \
              --tag inference:$IMAGE_TAG \
              --tag inference:$COMMIT_HASH \
              -f Dockerfile .

            docker images
            docker run -d -p 8000:8000 --name inference_container inference:latest


      - name: Push Docker Image to GCR
        run: |
            echo "GCR Host: $GCR_HOST"
            
            docker tag inference:latest $GCR_HOST/${{ secrets.GCP_PROJECT_ID }}/$GCR_REPOSITORY/inference:latest
            gcloud auth configure-docker $GCR_HOST -y
            docker push $GCR_HOST/${{ secrets.GCP_PROJECT_ID }}/$GCR_REPOSITORY/inference:latest
